-- ==========================================
-- keymaps.lua — 全局快捷键映射
-- 部署路径: .config/nvim/lua/core/keymaps.lua
-- 所属包: nvim/
-- 功能: Leader 键、窗口导航、Buffer 管理、LSP、Git、AI 等快捷键
-- ==========================================
local map = vim.keymap.set
local opts = { noremap = true, silent = true, desc = "" }
local function keymap(mode, lhs, rhs, desc)
  map(mode, lhs, rhs, vim.tbl_extend("force", opts, { desc = desc }))
end

-- ======== 插入模式 ========
map("i", "jk", "<Esc>", opts)
map("i", "kj", "<Esc>", opts)
map("c", "<C-a>", "<Home>", opts)
map("c", "<C-e>", "<End>", opts)

-- ======== 窗口导航 (smart-splits) ========
keymap("n", "<C-h>", function()
  require("smart-splits").move_cursor_left()
end, "左窗口")
keymap("n", "<C-j>", function()
  require("smart-splits").move_cursor_down()
end, "下窗口")
keymap("n", "<C-k>", function()
  require("smart-splits").move_cursor_up()
end, "上窗口")
keymap("n", "<C-l>", function()
  require("smart-splits").move_cursor_right()
end, "右窗口")
keymap("n", "<A-h>", function()
  require("smart-splits").resize_left()
end, "缩小")
keymap("n", "<A-j>", function()
  require("smart-splits").resize_down()
end, "缩小")
keymap("n", "<A-k>", function()
  require("smart-splits").resize_up()
end, "放大")
keymap("n", "<A-l>", function()
  require("smart-splits").resize_right()
end, "放大")
keymap("n", "<leader>Wh", function()
  require("smart-splits").move_cursor_left()
end, "窗口左移")
keymap("n", "<leader>Wj", function()
  require("smart-splits").move_cursor_down()
end, "窗口下移")
keymap("n", "<leader>Wk", function()
  require("smart-splits").move_cursor_up()
end, "窗口上移")
keymap("n", "<leader>Wl", function()
  require("smart-splits").move_cursor_right()
end, "窗口右移")

-- ======== 搜索 (snacks.picker) ========
keymap("n", "<leader>ff", function()
  Snacks.picker.files()
end, "查找文件")
keymap("n", "<leader>fg", function()
  Snacks.picker.grep()
end, "全文搜索")
keymap("n", "<leader>fb", function()
  Snacks.picker.buffers()
end, "缓冲区")
keymap("n", "<leader>fh", function()
  Snacks.picker.help()
end, "帮助标签")
keymap("n", "<leader>fr", function()
  Snacks.picker.resume()
end, "恢复搜索")
keymap("n", "<leader>fp", function()
  Snacks.picker.files({ cwd = vim.fn.expand("%:p:h") })
end, "当前目录文件")
keymap("n", "<leader>f.", function()
  Snacks.picker.recent()
end, "最近文件")
keymap("n", "<C-p>", function()
  Snacks.picker.keymaps()
end, "命令面板")

-- ======== 文件管理器 (Snacks Explorer) ========
keymap("n", "<leader>n", function()
  Snacks.explorer()
end, "文件管理器")
keymap("n", "-", function()
  Snacks.explorer()
end, "文件管理器")

-- ======== 标签页 (term: <leader>t) ========
keymap("n", "<leader>tn", "<cmd>tabnew<CR>", "新建标签")
keymap("n", "<leader>th", "<cmd>tabprev<CR>", "左标签")
keymap("n", "<leader>tl", "<cmd>tabnext<CR>", "右标签")
keymap("n", "<leader>tc", "<cmd>tabclose<CR>", "关闭标签")
keymap("n", "<leader>to", "<cmd>tabonly<CR>", "只留当前")
keymap("n", "<leader>t1", "<cmd>tabn 1<CR>", "标签 1")
keymap("n", "<leader>t2", "<cmd>tabn 2<CR>", "标签 2")
keymap("n", "<leader>t3", "<cmd>tabn 3<CR>", "标签 3")
keymap("n", "<leader>t4", "<cmd>tabn 4<CR>", "标签 4")
keymap("n", "<leader>t5", "<cmd>tabn 5<CR>", "标签 5")
keymap("n", "<leader>t6", "<cmd>tabn 6<CR>", "标签 6")
keymap("n", "<leader>t7", "<cmd>tabn 7<CR>", "标签 7")
keymap("n", "<leader>t8", "<cmd>tabn 8<CR>", "标签 8")
keymap("n", "<leader>t9", "<cmd>tabn 9<CR>", "标签 9")

-- ======== Buffer 导航 ========
keymap("n", "<Tab>", "<cmd>BufferLineCycleNext<CR>", "下一个 Buffer")
keymap("n", "<S-Tab>", "<cmd>BufferLineCyclePrev<CR>", "上一个 Buffer")
keymap("n", "<A-i>", "<cmd>BufferLineCycleNext<CR>", "下一个 Buffer")
keymap("n", "<A-o>", "<cmd>BufferLineCyclePrev<CR>", "上一个 Buffer")
keymap("n", "<A-q>", function()
  Snacks.bufdelete()
end, "关闭 Buffer")
keymap("n", "<A-1>", "<cmd>BufferLineGoToBuffer 1<CR>", "Buffer 1")
keymap("n", "<A-2>", "<cmd>BufferLineGoToBuffer 2<CR>", "Buffer 2")
keymap("n", "<A-3>", "<cmd>BufferLineGoToBuffer 3<CR>", "Buffer 3")
keymap("n", "<A-4>", "<cmd>BufferLineGoToBuffer 4<CR>", "Buffer 4")
keymap("n", "<A-5>", "<cmd>BufferLineGoToBuffer 5<CR>", "Buffer 5")
keymap("n", "<A-6>", "<cmd>BufferLineGoToBuffer 6<CR>", "Buffer 6")
keymap("n", "<A-7>", "<cmd>BufferLineGoToBuffer 7<CR>", "Buffer 7")
keymap("n", "<A-8>", "<cmd>BufferLineGoToBuffer 8<CR>", "Buffer 8")
keymap("n", "<A-9>", "<cmd>BufferLineGoToBuffer 9<CR>", "Buffer 9")
keymap("n", "<A-S-i>", "<cmd>BufferLineMoveNext<CR>", "Buffer 右移")
keymap("n", "<A-S-o>", "<cmd>BufferLineMovePrev<CR>", "Buffer 左移")
keymap("n", "<leader>bn", "<cmd>BufferLineCycleNext<CR>", "下一个 Buffer")
keymap("n", "<leader>bp", "<cmd>BufferLineCyclePrev<CR>", "上一个 Buffer")
keymap("n", "<leader>bd", function()
  Snacks.bufdelete()
end, "关闭 Buffer")

-- ======== 编辑器 ========
keymap("n", "<leader>h", "<cmd>nohlsearch<CR>", "清除搜索高亮")
keymap("n", "<leader>rr", "<cmd>redraw!<CR>", "屏幕重绘")
map("v", "p", function()
  if vim.bo.modifiable then
    vim.cmd('normal! "_dP')
  end
end, { noremap = true, silent = true, desc = "粘贴不丢失" })
map("v", "J", ":m '>+1<CR>gv=gv", opts)
map("v", "K", ":m '<-2<CR>gv=gv", opts)
keymap("n", "Y", "y$", "复制到行尾")
keymap("n", "n", "nzzzv", "下一个")
keymap("n", "N", "Nzzzv", "上一个")

-- ======== 包管理 (lazy.nvim) ========
keymap("n", "<leader>ph", "<cmd>Lazy<CR>", "包管理: 面板")
keymap("n", "<leader>ps", "<cmd>Lazy sync<CR>", "包管理: 同步")
keymap("n", "<leader>pu", "<cmd>Lazy update<CR>", "包管理: 更新")
keymap("n", "<leader>pi", "<cmd>Lazy install<CR>", "包管理: 安装")
keymap("n", "<leader>pl", "<cmd>Lazy log<CR>", "包管理: 日志")
keymap("n", "<leader>pc", "<cmd>Lazy check<CR>", "包管理: 检查")
keymap("n", "<leader>pp", "<cmd>Lazy profile<CR>", "包管理: 性能")
keymap("n", "<leader>pr", "<cmd>Lazy restore<CR>", "包管理: 恢复")
keymap("n", "<leader>px", "<cmd>Lazy clean<CR>", "包管理: 清理")

-- ======== 保存 / 退出 ========
keymap({ "n", "i" }, "<C-s>", "<cmd>w<CR>", "保存")
keymap("n", "<leader>q", "<cmd>q<CR>", "退出")
keymap("n", "<leader>Q", "<cmd>qa<CR>", "全部退出")

-- ======== 终端 (snacks.terminal) ========
map("t", "<Esc><Esc>", [[<C-\><C-n>]], opts)
keymap("t", "<A-d>", function()
  require("snacks").terminal(nil, { position = "float" })
end, "浮动终端")
keymap("n", "<A-d>", function()
  require("snacks").terminal(nil, { position = "float" })
end, "浮动终端")
keymap({ "n", "i", "t" }, "<C-\\>", function()
  require("snacks").terminal.toggle()
end, "切换终端")
keymap("n", "<leader>tt", function()
  require("snacks").terminal.toggle()
end, "切换终端")

-- ======== 格式化 ========
keymap("n", "<A-f>", function()
  vim.g.disable_autoformat = not vim.g.disable_autoformat
  vim.notify("格式保存: " .. (vim.g.disable_autoformat and "关" or "开"))
end, "切换格式保存")
keymap("n", "<A-S-f>", function()
  require("conform").format()
end, "手动格式化")

-- ======== AI 行内补全 (Supermaven) ========
keymap("n", "<leader>aa", function()
  require("supermaven-nvim.api").toggle()
end, "切换 AI 补全")

-- ======== AI (Opencode / Codex) 由外部 CLI 工具处理 ========

-- ======== Git 操作 ========
local g = require("core.git")
keymap("n", "<leader>gs", function()
  g.status()
end, "Git 状态")
keymap("n", "<leader>gc", function()
  g.commit()
end, "Git 提交")
keymap("n", "<leader>gC", function()
  g.commit_all()
end, "Git 全部提交")
keymap("n", "<leader>gp", function()
  g.push()
end, "Git 推送")
keymap("n", "<leader>gP", function()
  g.pull()
end, "Git 拉取")
keymap("n", "<leader>gl", function()
  g.log()
end, "Git 日志")
keymap("n", "<leader>gb", function()
  g.branch()
end, "Git 分支")
keymap("n", "<leader>gd", function()
  g.diff()
end, "Git Diff")
keymap("n", "<leader>gK", function()
  g.clone()
end, "Git 克隆")

-- ======== 运行代码 (内置 :term, 复用单终端) ========
keymap("n", "<leader>r", function()
  require("core.runner").run_current_file()
end, "运行代码")
keymap("n", "<leader>rv", function()
  require("core.runner").verify_project()
end, "验证项目")
